# Generated by Django 5.1.5 on 2025-01-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('code', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brandname', models.TextField(blank=True, db_column='brandName', null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('slno', models.UUIDField(primary_key=True, serialize=False)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('nutrients', models.TextField(blank=True, null=True)),
                ('score', models.TextField(blank=True, null=True)),
                ('nutri', models.TextField(blank=True, db_column='Nutri', null=True)),
                ('allergens', models.TextField(blank=True, null=True)),
                ('hazard', models.TextField(blank=True, null=True)),
                ('long', models.TextField(blank=True, db_column='Long', null=True)),
            ],
            options={
                'db_table': 'History',
                'db_table_comment': 'This is a duplicate of Saved',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('code', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brandname', models.TextField(blank=True, db_column='brandName', null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('slno', models.UUIDField(primary_key=True, serialize=False)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('nutrients', models.TextField(blank=True, null=True)),
                ('score', models.TextField(blank=True, null=True)),
                ('nutri', models.TextField(blank=True, db_column='Nutri', null=True)),
                ('allergens', models.TextField(blank=True, null=True)),
                ('hazard', models.TextField(blank=True, null=True)),
                ('long', models.TextField(blank=True, db_column='Long', null=True)),
            ],
            options={
                'db_table': 'Saved',
                'db_table_comment': 'This is a duplicate of History',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.TextField(db_column='user_Id', primary_key=True, serialize=False)),
                ('gmail', models.EmailField(db_column='Gmail', max_length=254)),
                ('fname', models.TextField(blank=True, db_column='Fname', null=True)),
                ('lname', models.TextField(blank=True, db_column='Lname', null=True)),
                ('age', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activity', models.TextField(blank=True, null=True)),
                ('diet', models.TextField(blank=True, null=True)),
                ('lifestyle', models.TextField(blank=True, null=True)),
                ('disease', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('sugar', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cholestrol', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('heartrate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
